name: "Bearer"
description: "Scan your source code to discover and classify data flow, and identify data security risks across your applications"
author: "Cédric Fabianski"
branding:
  icon: "lock"
  color: "blue"
inputs:
  github_token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
